//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Link { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> DateRead { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Favorite { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
